/*1)
Se desea desarrollar un programa que permita al usuario ingresar el valor en dólares de una criptomoneda en diferentes momentos, solicitando nombre del activo digital, valor, fecha de ingreso.
Realizar las siguientes operaciones:

A - Calcular el promedio de los valores ingresados.
B - Realizar una búsqueda para determinar si el valor de la criptomoneda en el último ingreso es mayor o menor al promedio calculado.
C - Encontrar el valor máximo y minimo ingresado, con la fecha en la que sucedió.
D - Si la AFIP se entero que compraron 5 unidades de este activo, calcular el 87% en impuestos sobre el precio pesificado. (Cotizacion 1 USD - 405 ARS) 

2) 
Se desea desarrollar un programa que permita al usuario ingresar el nombre, año emitido (Superior a 2000), si es online u offline y costo 5 videojuegos.
Realizar las siguientes operaciones:

A - Encontrar el videojuego más caro y el más barato ingresado.
B - Calcular el promedio de los costos de los videojuegos, pero solo para aquellos que son online.
C - Encontrar los videojuegos con el costo máximo y mínimo de aquellos emitidos antes de 2015.
D - Calcular el porcentaje de videojuegos offline en relación al total de videojuegos ingresados.

3)
Se desea desarrollar un programa que permita al usuario ingresar la forma del ovni avistado (circular, triangular, hexagonal), la fecha del avistamiento, el lugar donde se observó y el horario en que ocurrió el avistamiento, para luego realizar las siguientes operaciones:

A - Encontrar la forma de ovni más avistada en el conjunto de datos ingresado.
B - Buscar los avistamientos que se hayan producido en horarios nocturnos (entre las 20:00 y las 06:00).
C - Cual es la primer y ultima ciudad donde se produjo los avistamiento registrado.
D - Porcentaje sobre el total ingresado para cada forma observada. */
function mostrar() 
{
    
}